### ISSUE TITLE
nerdtree icon broken

### ISSUE THREAD

**Issue by vimniky** [jordwalke/VimBox#20]
<img width="217" alt="screen shot 2016-05-02 at 12 31 15 am" src="https://cloud.githubusercontent.com/assets/11426875/14942894/4278dc8c-0ffd-11e6-90cd-a2e3a8bf5def.png">

Can your help me solve this problem? thanks !

**Comment by jordwalke** [comment]
Only some fonts support this. Which Font are you using?

**Comment by vimniky** [comment]
I'm using Monaco . can you tell me what fonts are supported ?

**Comment by jordwalke** [comment]
This is the project:
https://github.com/ryanoasis/vim-devicons

Those fonts work with the NERDTree. Perhaps some of those patched fonts should be included in `VimBox` by default.

**Comment by vimniky** [comment]
Thanks ! I still can't solve this problem,so I just don't use those icon and fonts anymore .

**Comment by ryanoasis** [comment]
@vimniky If you still need help I can try to debug it with you. Feel free to ping on Gitter chat [here](https://gitter.im/ryanoasis/vim-devicons) or [here](https://gitter.im/ryanoasis/nerd-fonts).
