### ISSUE TITLE
MacVim looking strange after using VimBox

### ISSUE THREAD

**Issue by Robert-M-Muench** [jordwalke/VimBox#21]
![screenshot 2016-05-29 16 13 24](https://cloud.githubusercontent.com/assets/1826391/18719453/b5afc2a2-8027-11e6-8bdd-0b7768c4368a.PNG)

Somehow it looks strange on my system. I think the status line text is too big and it shows screwed up characters. Any idea?

**Comment by Robert-M-Muench** [comment]
I fixed the missing screenshot... hopefully somebody has an idea. It's still the same with the latest VIM & VimBox version.

**Comment by jordwalke** [comment]
It expects you to install an airline font to make the status bar awesome. I think the readme explains how to install one of these fonts. They come with MacVim

**Comment by jordwalke** [comment]
Or they come with VimBox I meant to say.

**Comment by Robert-M-Muench** [comment]
Hm... I have installed the fonts on OSX. But get the same result... How can I check which font is used? I haven't found anything where the font is configured.

**Comment by jordwalke** [comment]
What does it say when you do `:set guifont?`

**Comment by Robert-M-Muench** [comment]
guifont=Menlo:12

That doesn't look correct... Thanks for the hint.

Adding to "vimrc.custom.after":
`set guifont=Inconsolata-dz\ for\ Powerline:h12`

solves the problem.
