### ISSUE TITLE
Startup-Error when using MacPort vim with VimBox

### ISSUE THREAD

**Issue by Robert-M-Muench** [jordwalke/VimBox#22]
mac-pro:VimBox robby$ vim
UltiSnips requires py >= 2.7 or py3
Betätigen Sie die EINGABETASTE oder geben Sie einen Befehl ein

But python is installed.

**Comment by jordwalke** [comment]
But did you install write Python enabled in the Mac port Vim? The instructions mention which vim this works with.

**Comment by Robert-M-Muench** [comment]
Ok, the version MacPorts installed by default doesn't has Python included. 

> sudo port install vim +cscope +huge +lua +python35

did the trick

**Comment by jordwalke** [comment]
I haven't tried any Mac ports but if you end up discovering an install process there that works, we can add it to list of supported MacVim builds. Until then, no promises anything works.

**Comment by Robert-M-Muench** [comment]
The vim (CLI version) via MacPorts works now as described above.

**Comment by Robert-M-Muench** [comment]
When using the binary from MacVim add this line to .vimrc to get it all working when using MacPorts Python:

let $PYTHONHOME="/opt/local/Library/Frameworks/Python.framework/Versions/Current"

**Comment by jordwalke** [comment]
Is there a reason to use the macports python instead of the default one?

**Comment by Robert-M-Muench** [comment]
Well, if you use macports you can get their Python installed as a dependency of something. Since macports takes higher priority in the search path, you know use the macports Python.

Overall it would make sense to cross-check if a macports Python is present and maybe ask the user which one to use or reference the macports version.

**Comment by jordwalke** [comment]
Yeah, sounds like a reasonable idea. If you can come up with a little snippet that does that, I'd be glad to include it so everyone can benefit.

**Comment by Robert-M-Muench** [comment]
I'm far from being a bash expert, here is a snippet that returns the macports Python path of the current active used Phyton version:

`#!/bin/bash
a=$(which python) 
a+="-config"
echo $a
if read -r line < $a &>/dev/null ; then
  echo macports pyhton used
  echo $line
  ppath=${line%s/*}
  ppath+="/Current"
  echo $ppath
else
  echo no macports phyton used
fi
`

I'm sure it's not bullet proof but since we only target OSX, it should work.
