### ISSUE TITLE
Question mark characters

### ISSUE THREAD

**Issue by apucacao** [jordwalke/VimBox#30]
Hey all,

Thanks for VimBox! I'm just now trying to get back into using vim to see what's changed.

I followed the README, but I just noticed that there are several weird characters in the status line:

![ld-launched-bulk-targeting md__dropboxdrafts_-_vim_2016-10-27_09-59-46](https://cloud.githubusercontent.com/assets/232396/19777259/398067e2-9c2c-11e6-83ae-d779bcc643b5.jpg)

Any idea what those are?

Thanks,

Alexis

**Comment by jordwalke** [comment]
This is using `vim-airline`, which expects that you use patched fonts by default. VimBox includes them and the installation instructions have a step which would enable them.

**Comment by jordwalke** [comment]
<img width="494" alt="screen shot 2016-10-27 at 1 57 18 pm" src="https://cloud.githubusercontent.com/assets/977348/19785171/51840b8e-9c4d-11e6-916a-7f8a7cecdf4f.png">

With the fonts, it looks awesome like this.
It would be great if someone would send a PR that detects if the user is using a `guifont` that supports airline arrow symbols and then automatically turns on the arrows based on that.

**Comment by jordwalke** [comment]
Reopen if needed.
