### ISSUE TITLE
NerdTree Won't Open Directory

### ISSUE THREAD

**Issue by pertrai1** [jordwalke/VimBox#42]
When I added this and fired it up for the first time, I toggled NerdTree and was able to move up and down, but not able to open any directory. Anyone have this issue they have resolved before?

**Comment by jordwalke** [comment]
You can hit enter on a file to open the file in a new tab, or you can hit `o` on a directory to expand the directory.

**Comment by pertrai1** [comment]
AWESOME!! I am liking this a lot. Looking through the files now. Would like to use a light theme like I do in ST3. Will look at that separately as that does not deal with this issue. Thank you

**Comment by jordwalke** [comment]
You can use the build in colorscheme `one`. It should be the default IIRC. Just do `:set background-light`. It's pretty great.
