### ISSUE TITLE
Reason support

### ISSUE THREAD

**Issue by kennetpostigo** [jordwalke/VimBox#44]
So I just did a fresh install of vimbox and there seem to be a few issues:
![image](https://cloud.githubusercontent.com/assets/8888991/25106893/0e9cbfbc-239a-11e7-8840-1e34c9c362bb.png)

After following the instructions I noticed the following things missing from vimbox:

+ I don't seem to be getting any syntax highlighting on Reason files.
+ No type hinting
+ Line numbers don't appear
+ ~~I have the powerline fonts installed and the recommended fonts installed in fontbook but vimbox doesn't seem to pick it up.~~

EDIT: I ran the install script and now fonts appear to work.

**Comment by jordwalke** [comment]
Thanks for reporting! Did you install reason-cli? Or did you install Reason from opam? Either should work. 

Inside of `~/.vim/bundlesVimRc` it has the following:

```
Plug 'reasonml/vim-reason-loader'
source ~/.vim/pluginRc/vimReasonVimRc
let g:merlin_split_method = "vertical"
```

Which is a plugin that will load Reason from the global path for any of the standard installs for `merlin`, and `reason`. Reason uses the same convention that merlin uses, so if you install using reason-cli or opam, it should always work. How did you install reason and merlin?

**Comment by kennetpostigo** [comment]
I have reason installed through reason-cli but I also have reason and merlin installed through opam since moving to ReasonNativeProject. I'll check the content of bundlesVimRC now.

**Comment by jordwalke** [comment]
Debugged with @kennetpostigo. zsh setup was corrupting his path.
