### ISSUE TITLE
Minor Note on Icon Change

### ISSUE THREAD

**Issue by idkjs** [jordwalke/VimBox#47]
Changing .icns file on symlinked/aliased apps seems to have changed in Sierra so your icon change step doesn't work as written. ref: <https://discussions.apple.com/thread/7720713?start=0&tstart=0> with possible work around.

**Comment by oscarmcm** [comment]
I've followed these steps:
- Find the MacVim app installed by brew
   - /usr/local/Cellar/macvim/<VERSION>
- Change the icon following the steps in the docs
- linkapp with brew
- voilà
![image](https://user-images.githubusercontent.com/2553459/36431758-02ac2414-161e-11e8-9c2a-b0e6135fd107.png)
