### ISSUE TITLE
autocomplete not working at all...

### ISSUE THREAD

**Issue by Robert-M-Muench** [jordwalke/VimBox#52]
I had to re-install vimbox after I upgraded to High Sierra and the fitting MacPorts due to some Python annoyances.

However, since all this autocomplete is not working anymore. Neither is the brace expansion etc.

Any hint how to drill down the problem? Which plug-in is it?

**Comment by jordwalke** [comment]
If neither of those are working, that seems weird because those are two separate plugins. It's almost as if none of the plugins are working.

**Comment by Robert-M-Muench** [comment]
Things like NerdTree and the status bar are working... And here is the output of PlugStatus:
`Finished. 0 error(s).
[==========================================]

- vim-reason: OK
- vim-expand-region: OK
- splitjoin.vim: OK
- MacVimSmartGUITabs: OK
- VimSplitBalancer: OK
- undoquit.vim: OK
- far.vim: OK
- vim-colors-solarized: OK
- ocp-indent-vim: OK
- VimAutoMakeDirectory: OK
- vim-smooth-scroll: OK
- vim-repeat: OK
- VimJSDocSnippets: OK
- csv.vim: OK
- gitv: OK
- nerdtree: OK
- VimLastTab: OK
- gundo.vim: OK
- flatlandia: OK
- vim-mucomplete: OK
- JavaScript-Indent: OK
- vim-fugitive: OK
- vim-one: OK
- ultisnips: OK
- vim-misc: OK
- vim-airline-themes: OK
- vim-surround: OK
- vim-PairTools: OK
- VimCleanColors: OK
- vim-jsx: OK
- vim-sensible: OK
- vim-javascript: OK
- ctrlp.vim: OK
- incsearch.vim: OK
- vim-airline: OK
- syntastic: OK
- grep: OK
- VimCloser: OK
- nerdcommenter: OK
- Parameter-Text-Objects: OK
- vim-session: OK
- vim-markdown: OK`

**Comment by Robert-M-Muench** [comment]
Ok, so found the problem. The default syntax setting for .cpp file extension was/is objcc, which is missing those features. If I change it to cpp things work.

Maybe the default syntax settings are wrong? Where can I find them?

**Comment by jordwalke** [comment]
I might have had an old hack in there that set the filetype to objcc - which isn't appropriate in the open source VimBox.

**Comment by jordwalke** [comment]
Fixed in master with [this change](https://github.com/jordwalke/VimBox/commit/21fb09817dee63f86fec747225fb387cd4ace33b#diff-a067d708495e50e346691a5a8d455745).
