### ISSUE TITLE
Showing hidden files in VimBox/MacVim

### ISSUE THREAD

**Issue by idkjs** [jordwalke/VimBox#58]
In the image below, there is a `.env` file. VimBox is not showing hidden files in the nerdtree menu. How do I enable that?

<img width="850" alt="screen shot 2018-05-07 at 10 32 10 am" src="https://user-images.githubusercontent.com/2370391/39692731-f6fef24a-51e1-11e8-9d41-26ad178f7ced.png">

Thank you.

**Comment by motiko** [comment]
either press `I` (shift + i) when in NERD_Tree or run 
`let NERDTreeShowHidden=1`

[see this SO question ](
https://stackoverflow.com/questions/5057359/how-can-i-show-hidden-files-starting-with-period-in-nerdtree/5057406)

**Comment by idkjs** [comment]
@motiko done. thank you, sir.
