### ISSUE TITLE
enter key throws error in insert mode

### ISSUE THREAD

**Issue by paultopia** [jordwalke/VimBox#64]
Hi there,

I'm using a fresh clone of VimBox as of today (from commit f56c141 ), and a fresh release of MacVim (snapshot 154), with no customizations. I literally just installed it and am trying it out.

In insert mode, the enter key doesn't work.  When I hit enter to get a newline, both in GUI and in terminal mode it displays the following error: 

```
E117: Unknown function: mucomplete#popup_exit
Press ENTER or type command to continue
```

pressing enter just repeats the error, though pressing escape clears it.

**Comment by maljukan** [comment]
This fixed it for me:  
https://github.com/lifepillar/vim-mucomplete/issues/108

Apparently `inoremap` for key bindings are not needed any more.  

Removing:
```
" inoremap <expr> <c-e> mucomplete#popup_exit("\<c-e>")
" inoremap <expr> <tab> mucomplete#popup_exit("\<c-y>")
inoremap <expr>  <cr> mucomplete#popup_exit("\<cr>")
```
from `pluginRc/mucompleteVimRc` solved it.
