### ISSUE TITLE
Fonts/icons not working out of the box

### ISSUE THREAD

**Issue by dylanirlbeck** [jordwalke/VimBox#69]
So I just tried out the new VimBox on the `json` branch, and for the most part it worked great! It was extremely simple to set up and didn't mess with my existing Vim configurations. I do have one question, though, which is how can I get the font to be the same as the one in shown in the README. Currently, the font is as shown in the screenshot below. I also had some issues rendering icons (you can see the box with the ? inside it in the bottom status bar). Thanks in advance for your help!

<img width="829" alt="Screen Shot 2020-02-19 at 9 14 30 AM" src="https://user-images.githubusercontent.com/35497479/74847748-3dc66280-52f8-11ea-863b-6af98d739ddd.png">

**Comment by jordwalke** [comment]
You need a font with powerline symbols. I use PragmataPro (commercial), but there are many good fonts with powerline symbols. I could also add one to VimBox and make it the default.

**Comment by jordwalke** [comment]
I recommend `InconsolataDz` here: https://github.com/powerline/fonts

**Comment by jfrolich** [comment]
Great stuff! Because a config file is generated, and it looks like the default config is ignored. How to set the font persistently? I don't see an option in the json file.

**Comment by jordwalke** [comment]
In `~/.config/vim-box/user/settings.osx.gui.json` add something like:

```
    "vim": {
      "config": {
        "guifont": "PragmataPro_Mono_Liga:h10",
      },
     ...
```

**Comment by jordwalke** [comment]
The config will be regenerated when reopening VimBox.
